### ISSUE TITLE
 No translation file found for domain: 'app' 

### ISSUE THREAD

**Issue by ZhangYanZhe20** [FutureUniant/Tailor#7]
您好，请问这个该怎么解决？
(venv) PS C:\Users\zhang\Desktop\Tailor> python .\main.py                                                               
Traceback (most recent call last):                                                                                      
  File "C:\Users\zhang\Desktop\Tailor\main.py", line 35, in <module>                                                    
    app = App(tailor_path=tailor_path)                                                                                  
  File "C:\Users\zhang\Desktop\Tailor\app\template\app.py", line 47, in __init__                                        
    self.set_translate(self.language, WINDOW_NAME)                                                                      
  File "C:\Users\zhang\Desktop\Tailor\app\template\__init__.py", line 20, in set_translate                              
    self._translate = get_local_strings(language, window_name)                                                          
  File "C:\Users\zhang\Desktop\Tailor\app\template\locale\__init__.py", line 20, in get_local_strings                   
    locale = gettext.translation(window_name, localedir, languages=[domain])                                            
  File "C:\Users\zhang\AppData\Local\Programs\Python\Python310\lib\gettext.py", line 592, in translation                
    raise FileNotFoundError(ENOENT,                                                                                     
FileNotFoundError: [Errno 2] No translation file found for domain: 'app'

**Comment by FutureUniant** [comment]
首先感谢您对Tailor的关注！
对于您提到的问题，主要是因为没有翻译部分的文件，该部分的文件需要手动编译，通过使用
可以添加Tailor微信，持续关注！
Tailor客服微信

**Comment by FutureUniant** [comment]
首先感谢您对Tailor的关注！
对于您提到的问题，主要是因为没有翻译部分的文件，该部分的文件需要手动编译，通过使用[i18n_tools.py](https://github.com/FutureUniant/Tailor/blob/main/tools/i18n_tools.py)进行编译；
或者安装Tailor，然后寻找其中已经编译完成的文件！
可以加入Tailor用户群做详细了解！
